- name: gather  packages facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install nftables
  apt:
    name: nftables
    state: present
    update_cache: yes
  when: "'nftables' not in ansible_facts.packages"

- name: Ensure nftables is enabled and started
  systemd:
    name: nftables
    state: started
    enabled: true
  ignore_errors: true

- name: register status of /etc/nftables.d/
  stat:
    path: /etc/nftables.d/
  register: nft_dir

- name: Create nftables rule dir
  file:
    path: /etc/nftables.d
    state: directory
    mode: '0755'
  when: " not nft_dir.stat.exists"

#- name: Deploy nftables base rules
#  copy:
#    src: templates/base.rules.j2
#    dest: /etc/nftables.d/base.rules
#    mode: '0644'
#
#- name: Deploy nftables SSH access Rules
#  copy:
#    src: templates/ssh.rules.j2
#    dest: /etc/nftables.d/ssh.rules
#    mode: '0644'
#
#- name: Deploy nftables HTTP rules
#  copy:
#    src: templates/http.rules.j2
#    dest: /etc/nftables.d/http.rules
#    mode: '0644'
#  notify: Reload nftables

- name: Upload nftables configuration
  template:
    src: nft.conf.j2
    dest: /etc/nftables.conf
  notify: Reload nftables

