---
- name: Install and Configure infra 
  hosts: all
  become: true
  gather_facts: yes
  
  roles:
    - role: common
      tags: ['common']
    - role: nft
      tags: ['nft']
    - role: squid
      tags: ['proxy', 'squid']
    - role: softether
      tags: ['se', 'vpn_server']
    - role: route
      tags: ['route']

