---
- name: gather facts and save it
  hosts: all
  gather_facts: no

  tasks:
  - name: get packages
    ansible.builtin.package_facts:
      manager: auto
  
  - name: check whther a package are installed
    debug:
      msg: "{{ ansible_facts.packages['nftables']}} version of nftables are installed!"
    when: "'nftables' in ansible_facts.packages"