---
input_rules:

  - rule: ct state established,related counter accept
    comment: Allow established and related connections

  - rule: iif "lo" accept
    comment: "Allow traffic to the loopback interface"

  - rule: iif "tun0" counter accept
    comment: "Accept any on tunnel 0 interface"

  - rule: ct state invalid drop
    comment: Block unstablished traffics

  - rule: tcp dport 1701 counter accept
    comment: allow L2TP

  - rule: udp dport { isakmp, ipsec-nat-t } counter accept
    comment: "accept ISAKMP and IPsec NAT traversal"
  
  - rule: udp dport { 1723, 3271 } counter accept
    comment: Allow vpn access
  
  - rule: ip protocol esp counter accept
    comment: accept ESP

  - rule: ip saddr 212.227.61.231/32 counter log accept
    comment: DE server

  - rule: ip saddr 81.12.121.42/32 tcp dport { 22,443,5555 } counter accept
    comment: Lotusco Office

  - rule: ip saddr 51.79.60.201/32 tcp dport 5555 counter log accept
    comment: Morteza Sadeghi

  - rule: ip saddr 192.111.144.71/32 tcp dport 22 counter accept
    comment: Farshid VPN

  - rule: ip saddr 192.111.144.71/32 tcp dport 5555 counter accept
    comment: Farshid VPN

  - rule: ip saddr 185.78.23.43/32 tcp dport 443 counter log accept
    comment: Morteza Sadeghi
  
  - rule: ip saddr 185.78.23.43/32 tcp dport 5555 counter log accept
    comment: Morteza Sadeghi

  - rule: ip saddr 51.79.60.201/32 tcp dport 22 counter log accept
    comment: Morteza Sadeghi

  - rule: ip saddr 185.78.23.43/32 tcp dport 22 counter log accept
    comment: Morteza Sadeghi

  - rule: ip saddr 194.164.175.18/32 tcp dport 22 counter log accept
    comment: Morteza Sadeghi Spain

  - rule: counter drop
    comment: "count dropped packets"

forward_rules:
  - ip saddr 192.168.130.0/24 ip daddr 0.0.0.0/0 counter accept

output_rules:
  # Allow established and related connections
  - ct state established,related counter accept

  # Allow traffic to the localhost IP address
  - oif "lo" accept
  - oif "eth0" accept
  - oif "tun0" accept

  # DHCP client requests
  - udp dport 67 counter log accept
  - udp dport 68 counter log accept

  # DNS requests
  - udp dport 53 counter log accept