---
input_rules:

  - rule: ct state established,related counter accept
    comment: Allow established and related connections

  - rule: iif "lo" accept
    comment: "Allow traffic to the loopback interface"

  - rule: ct state invalid drop
    comment: Block unstablished traffics

  - rule: ip saddr 81.12.121.42/32 tcp dport { 22,443,5555 } counter accept
    comment: Lotusco Office

  - rule: ip saddr 51.79.60.201/32 tcp dport 5555 counter log accept
    comment: Morteza Sadeghi

  - rule: ip saddr 192.111.144.71/32 tcp dport 22 counter accept
    comment: Farshid VPN

  - rule: ip saddr 192.111.144.71/32 tcp dport 5555 counter accept
    comment: Farshid VPN

  - rule: ip saddr 185.78.23.43/32 tcp dport 443 counter log accept
    comment: Morteza Sadeghi
  
  - rule: ip saddr 185.78.23.43/32 tcp dport 5555 counter log accept
    comment: Morteza Sadeghi

  - rule: ip saddr 51.79.60.201/32 tcp dport 22 counter log accept
    comment: Morteza Sadeghi

  - rule: ip saddr 185.78.23.43/32 tcp dport 22 counter log accept
    comment: Morteza Sadeghi

  - rule: ip saddr 194.164.175.18/32 tcp dport 22 counter log accept
    comment: Morteza Sadeghi Spain

  - rule: log level info drop
    comment: Log and drop all other traffic

forward_rules:
# Add forward rules here

output_rules:
  # Allow established and related connections
  - ct state established,related counter accept

  # Allow traffic to the localhost IP address
  - oif "lo" accept
  - oif "eth0" accept
