- name: Configure SSH
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: Restart SSH

- name: Add SSH users
  user:
    name: "{{ item.name }}"
    state: present
    groups: "{{ item.groups | default('sudo') }}"
    append: yes
  loop: "{{ ssh_users }}"

- name: Upload authorized keys
  authorized_key:
    user: "{{ item.0.name }}"
    state: present
    key: "{{ item.1 }}"
  loop: "{{ ssh_users | subelements('key') }}"
