---
input_rules:

  - rule: ct state established,related counter accept
    comment: Allow established and related connections

  - rule: iif "lo" accept
    comment: "Allow traffic to the loopback interface"

  - rule: iif "tunn0" counter accept
    comment: "Accept any on tunnel 0 interface"

  - rule: iif "gre6" counter accept
    comment: "Accept any on tunnel 0 interface"

  - rule: ct state invalid drop
    comment: Block unstablished traffics

  - rule: udp dport 443 counter accept
    comment: allow openvpn connection to port 443

  - rule: ip saddr 192.168.131.0/24 counter accept
    comment: allow vpn client access
  
  - rule: ip saddr 192.168.130.0/24 counter accept
    comment: allow vpn clients on hub VPN

  - rule: ip saddr 185.105.239.186/32 counter accept
    comment: Lotusco Iran VPN Server
  
  - rule: ip saddr 81.12.121.42/32 tcp dport { 22,443,5555,2073,8443 } counter accept
    comment: Lotusco Office

  - rule: ip saddr 51.79.60.201/32 tcp dport 5555 counter log accept
    comment: Morteza Sadeghi

  - rule: ip saddr 192.111.144.71/32 tcp dport 22 counter accept
    comment: Farshid VPN

  - rule: ip saddr 192.111.144.71/32 tcp dport 5555 counter accept
    comment: Farshid VPN

  - rule: ip saddr 185.78.23.43/32 tcp dport 443 counter log accept
    comment: Morteza Sadeghi
  
  - rule: ip saddr 185.78.23.43/32 tcp dport 5555 counter log accept
    comment: Morteza Sadeghi

  - rule: ip saddr 51.79.60.201/32 tcp dport 22 counter log accept
    comment: Morteza Sadeghi

  - rule: ip saddr 185.78.23.43/32 tcp dport 22 counter log accept
    comment: Morteza Sadeghi

  - rule: ip saddr 194.164.175.18/32 tcp dport 22 counter log accept
    comment: Morteza Sadeghi Spain

  - rule: log level info drop
    comment: Log and drop all other traffic

forward_rules:
  - ip saddr 192.168.130.0/24 ip daddr 0.0.0.0/0 counter accept
  - ip saddr 192.168.131.0/24 ip daddr 0.0.0.0/0 counter accept
  - ip saddr 192.168.100.0/30 ip daddr 0.0.0.0/0 counter accept

output_rules:
  # Allow established and related connections
  - ct state established,related counter accept

  # Allow traffic to the localhost IP address
  - oif "lo" counter accept
  - oif "ens6" counter accept
  - oif "tunn0" counter accept
  - oif "gre6" counter accept

nat_rules:
  # nat vpn clients to ens6
  - oif "ens6" ip saddr 192.168.130.0/24 masquerade
  - oif "ens6" ip saddr 192.168.131.0/24 masquerade
  - oif "ens6" ip saddr 10.1.1.2/32 masquerade
  - oif "ens6" ip saddr 192.168.100.0/30 masquerade