enable_nat: true
nat_interfaces:
  - ens6
tunnel_name: tunn0
local_ipv6: 2001:db8:cafe::1
gateway_ipv6: 2001:db8:cafe::2
remote_ipv4: 185.105.239.186
local_ipv4: "{{ ansible_default_ipv4.address }}"
mtu: 1400

netplan_tunnels:
  - interface_name: tunn0
    addresses:
      - 2001:db8:cafe::1/64
    parameters:
      mode: sit
      local: 212.227.128.217
      remote: 185.105.239.156
      mtu: 1400

  - interface_name: tun1
    addresses:
      - 10.1.1.1/30
    parameters:
      mode: ipip6
      local: 2001:db8:cafe::1
      remote: 2001:db8:cafe::2
      ttl: 255
    routes:
      - to: 192.168.130.0/24
        via: 10.1.1.2
      - to: 192.168.131.0/24
        via: 10.1.1.2
      - to: 192.168.100.0/30
        via: 10.1.1.2
