---
- name: reload bind
  ansible.builtin.service:
    name: "{{ bind_service }}"
    state: reloaded

- name: restart bind
  ansible.builtin.service:
    name: "{{ bind_service }}"
    state: restarted

- name: Reload AppArmor
  ansible.builtin.service:
    name: apparmor
    state: reloaded