ssh_port: 22
gracetime: 60
max_auth: 4
max_session: 6
ClientAliveInterval: 300
ClientAliveCountMax: 3
ssh_allowed_users: [ mosadeghi root ]
root_login: "yes"

ssh_users:
  - name: mosadeghi
    key: 
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK7ieuhmDyRM3CmqHhIag38aZooiJ5yxb2MKj0KqzdzW" 
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJhU6kBz7cv30KThyWgqJR09cBom+wKJQ8Fp2IxSzi+x"