ssh_port: 22
gracetime: 60
max_auth: 4
max_session: 6
ClientAliveInterval: 300
ClientAliveCountMax: 3
allowed_group: [ mosadeghi admin ]
root_login: "yes"

ssh_users:
  - name: mosadeghi
    key: 
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPnsG0JUNHqqEzGbxTG/nYooEXVEnDOfBB2fYzbWeHSp sadeghi@tebyanidc.ir" 
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK7ieuhmDyRM3CmqHhIag38aZooiJ5yxb2MKj0KqzdzW morteza.sadeghi@outlook.com"