---
- name: include tasks
  include_tasks: dependencies.yml

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: make prefix directory
  file:
    path: "{{ se_prefix }}"
    state: directory

- name: download softether vpn server source
  get_url:
    url: 'http://softether-download.com/files/softether/{{ se_version }}-tree/Linux/SoftEther_VPN_Server/64bit_-_Intel_x64_or_AMD64/softether-vpnserver-{{ se_version }}-linux-x64-64bit.tar.gz'
    dest: '{{ tmpdir }}/softether-vpnserver-{{ se_version }}-linux-x64-64bit.tar.gz'
  when: "'softether-vpnserver' not in ansible_facts.packages"
  register: download

- name: download softether vpn client source
  get_url:
    url: 'http://softether-download.com/files/softether/{{ se_version }}-tree/Linux/SoftEther_VPN_Client/64bit_-_Intel_x64_or_AMD64/softether-vpnclient-{{ se_version }}-linux-x64-64bit.tar.gz'
    dest: '{{ tmpdir }}/softether-vpnserver-{{ se_version }}-linux-x64-64bit.tar.gz'
  when: 
    - "'softether-client' not in ansible_facts.packages"
    - "'vpn.lotusco.co' in inventory_hostname"
  register: download

- name: upload softether vpn client file
  copy:
    src: files/softether-vpnclient-{{ se_version }}-linux-x64-64bit.tar.gz
    dest: /tmp/
    force: no

- name: unarchive vpn server
  unarchive:
    remote_src: true
    src: "{{ tmpdir }}/softether-vpnserver-{{ se_version }}-linux-x64-64bit.tar.gz"
    dest: "{{ se_dir }}"
  #when: download.changed
  register: unarchive

- name: unarchive vpn client
  unarchive:
    remote_src: true
    src: "{{ tmpdir }}/softether-vpnclient-{{ se_version }}-linux-x64-64bit.tar.gz"
    dest: "{{ se_dir }}"
  #when: download.changed
  register: unarchive

- name: make vpnserver
  shell: yes 1 | make
  args:
    chdir: "{{ se_dir }}/vpnserver"
  #when: unarchive.changed
  register: make

- name: make vpnclient
  shell: yes 1 | make
  args:
    chdir: "{{ se_dir }}/vpnclient"
  #when: unarchive.changed
  register: make

- name: configure vpnserver lang.config
  lineinfile:
    dest: "{{ se_dir }}/vpnserver/lang.config"
    regexp: "^(en|ja|cn)$"
    line: "{{ se_lang }}"
  #when: make.changed

# - name: configure vpn client lang.config
#   lineinfile:
#     dest: "{{ se_dir }}/vpnclient/lang.config"
#     regexp: "^(en|ja|cn)$"
#     line: "{{ se_lang }}"
#   #when: make.changed

- name: install init script for vpn server
  template: >
    src=vpnserver.j2
    dest=/etc/init.d/vpnserver.sh
    mode=0755
- name: install init script for vpn client
  template: >
    src=vpnclient.j2
    dest=/etc/init.d/vpnclient.sh
    mode=0755

- name: Configure Systemd service for vpn server
  template:
    src: softether-vpnserver.j2
    dest: /etc/systemd/system/softether-vpnserver.service
    mode: '0755'

- name: Configure Systemd service for vpn Client
  template:
    src: softether-vpnclient.j2
    dest: /etc/systemd/system/softether-vpnclient.service
    mode: '0755'

- name: start softether-vpnserver vpn service
  service:
    name: softether-vpnserver
    enabled: yes
    daemon_reload: true
    state: started

- name: start softether-vpnclient vpn service
  service:
    name: softether-vpnclient
    enabled: yes
    daemon_reload: true
    state: started

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes