bind_zones:
  - name: fanhab.local
    serial: 1000
    ttl: 86400
    soa_ns: ns1.example.com.
    soa_email: admin.example.com.        # dot instead of @
    ns_records:
      - ns1.example.com.
      - ns2.example.com.
    a_records:
      - { name: "ns1",  ip: "192.168.1.10" }
    cname_records:
      - { name: "mx", target: "mail.example.com." }

bind_reverse_zones:
  - name: 200.255.134.in-addr.arpa
    serial: 100200
    ttl: 86400
    soa_ns: rdns1.fanhab.ir.
    soa_email: admin.fanhab.ir
    ns_records:
      - rdns1.fanhab.ir.
      - rdns2.fanhab.ir.
    ptr_records:
  
  - name: 201.255.134.in-addr.arpa
    serial: 100201
    ttl: 86400
    soa_ns: rdns1.fanhab.ir.
    soa_email: admin.fanhab.ir
    ns_records:
      - rdns1.fanhab.ir.
      - rdns2.fanhab.ir.
    ptr_records:

  - name: 202.255.134.in-addr.arpa
    serial: 100202
    ttl: 86400
    soa_ns: rdns1.fanhab.ir.
    soa_email: admin.fanhab.ir
    ns_records:
      - rdns1.fanhab.ir.
      - rdns2.fanhab.ir.
    ptr_records:

  - name: 203.255.134.in-addr.arpa
    serial: 100203
    ttl: 86400
    soa_ns: rdns1.fanhab.ir.
    soa_email: admin.fanhab.ir
    ns_records:
      - rdns1.fanhab.ir.
      - rdns2.fanhab.ir.
    ptr_records:

  - name: 204.255.134.in-addr.arpa
    serial: 100204
    ttl: 86400
    soa_ns: rdns1.fanhab.ir.
    soa_email: admin.fanhab.ir
    ns_records:
      - rdns1.fanhab.ir.
      - rdns2.fanhab.ir.
    ptr_records:

  
  - name: 205.255.134.in-addr.arpa
    serial: 100205
    ttl: 86400
    soa_ns: rdns1.fanhab.ir.
    soa_email: admin.fanhab.ir
    ns_records:
      - rdns1.fanhab.ir.
      - rdns2.fanhab.ir.
    ptr_records:

  - name: 206.255.134.in-addr.arpa
    serial: 100206
    ttl: 86400
    soa_ns: rdns1.fanhab.ir.
    soa_email: admin.fanhab.ir
    ns_records:
      - rdns1.fanhab.ir.
      - rdns2.fanhab.ir.
    ptr_records:

  - name: 207.255.134.in-addr.arpa
    serial: 100207
    ttl: 86400
    soa_ns: rdns1.fanhab.ir.
    soa_email: admin.fanhab.ir
    ns_records:
      - rdns1.fanhab.ir.
      - rdns2.fanhab.ir.
    ptr_records:

  - name: 168.214.31.in-addr.arpa
    serial: 100168
    ttl: 86400
    soa_ns: rdns1.fanhab.ir.
    soa_email: admin.fanhab.ir
    ns_records:
      - rdns1.fanhab.ir.
      - rdns2.fanhab.ir.
    ptr_records:

  - name: 169.214.31.in-addr.arpa
    serial: 100169
    ttl: 86400
    soa_ns: rdns1.fanhab.ir.
    soa_email: admin.fanhab.ir
    ns_records:
      - rdns1.fanhab.ir.
      - rdns2.fanhab.ir.
    ptr_records:

  - name: 170.214.31.in-addr.arpa
    serial: 100170
    ttl: 86400
    soa_ns: rdns1.fanhab.ir.
    soa_email: admin.fanhab.ir
    ns_records:
      - rdns1.fanhab.ir.
      - rdns2.fanhab.ir.
    ptr_records:

  - name: 171.214.31.in-addr.arpa
    serial: 100171
    ttl: 86400
    soa_ns: rdns1.fanhab.ir.
    soa_email: admin.fanhab.ir
    ns_records:
      - rdns1.fanhab.ir.
      - rdns2.fanhab.ir.
    ptr_records:

  - name: 172.214.31.in-addr.arpa
    serial: 100172
    ttl: 86400
    soa_ns: rdns1.fanhab.ir.
    soa_email: admin.fanhab.ir
    ns_records:
      - rdns1.fanhab.ir.
      - rdns2.fanhab.ir.
    ptr_records:

  - name: 173.214.31.in-addr.arpa
    serial: 100173
    ttl: 86400
    soa_ns: rdns1.fanhab.ir.
    soa_email: admin.fanhab.ir
    ns_records:
      - rdns1.fanhab.ir.
      - rdns2.fanhab.ir.
    ptr_records:

  - name: 174.214.31.in-addr.arpa
    serial: 100174
    ttl: 86400
    soa_ns: rdns1.fanhab.ir.
    soa_email: admin.fanhab.ir
    ns_records:
      - rdns1.fanhab.ir.
      - rdns2.fanhab.ir.
    ptr_records:

  - name: 175.214.31.in-addr.arpa
    serial: 100175
    ttl: 86400
    soa_ns: rdns1.fanhab.ir.
    soa_email: admin.fanhab.ir
    ns_records:
      - rdns1.fanhab.ir.
      - rdns2.fanhab.ir.
    ptr_records:

  - name: 209.32.194.in-addr.arpa
    serial: 100209
    ttl: 86400
    soa_ns: rdns1.fanhab.ir.
    soa_email: admin.fanhab.ir
    ns_records:
      - rdns1.fanhab.ir.
      - rdns2.fanhab.ir.
    ptr_records:
