---
input_rules:
  - ip6 saddr ::1 counter drop

  - ip saddr 127.0.0.1/8 counter drop

  - iif "lo" counter accept

  - ip protocol tcp ct state established counter accept

  - ip protocol udp ct state established counter accept

  - icmpv6 type { destination-unreachable, packet-too-big, time-exceeded, parameter-problem, mld-listener-query, mld-listener-report, mld-listener-done, nd-router-solicit, nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert, ind-neighbor-solicit, ind-neighbor-advert, mld2-listener-report } counter accept

  - icmp type {echo-request} counter accept

  - udp dport 53 counter accept

  - ip saddr 172.20.100.103/32 tcp dport 53 counter accept

  - ip saddr {172.16.3.3, 172.16.3.10, 192.168.20.69, 192.168.20.58} tcp dport 22 counter accept

  - ip protocol igmp counter accept

  - log level info counter drop

output_rules:
  # Allow established and related connections
  - ip protocol tcp ct state established,related,new counter accept
  - ip protocol udp ct state established,related,new counter accept
  - ip protocol icmp ct state established,related,new counter accept

  # Allow traffic to the localhost IP address
  - oif "lo" counter accept

  # Allow connection to Splunk DS and Indexer
  - ip daddr 172.20.15.50 tcp dport {8089,9997} counter accept
  
  # DNS requests
  - ip daddr {172.20.13.1,172.20.13.2,172.20.13.3} udp dport 53 counter accept
  - ip daddr 172.20.100.102/32 tcp dport 53 counter accept
  
  # Allow TimeSync(NTP)
  - ip daddr {172.20.51.1, 172.20.51.2} udp dport 123 counter accept

  # Block any other connection
  - log level info drop

