---
input_rules:

  - rule: ip protocol tcp ct state established counter accept
    comment: Allow established tcp connection

  - rule: ip protocol udp ct state established counter accept
    comment: Allow established udp connections

  - rule: ip saddr 172.16.3.3/32 tcp dport 22 counter accept
    comment: Morteza Sadeghi VPN IP

  - rule: ip saddr 172.16.3.10/32 tcp dport 22 counter accept
    comment: shahin ghoreishi VPN IP

  - rule: ip saddr 192.168.20.69/32 tcp dport 22 counter accept
    comment: Morteza Sadeghi LAN IP

  - rule: ip saddr 192.168.20.158/32 tcp dport 22 counter accept
    comment: SsHAhin ghoreishi LAN IP

  - rule: icmpv6 type { destination-unreachable, packet-too-big, time-exceeded, parameter-problem, mld-listener-query, mld-listener-report, mld-listener-reoprt} counter accept
    comment: Accept icmpv6

  - rule: icmp type {echo} counter accept
    comment: Accept icmp echo only

  - rule: udp dport 53 counter accept
    comment: allow public dns access

  - rule: counter drop
    comment: "count dropped packets"

output_rules:
  # Allow established and related connections
  - ip protocol tcp ct state established,related,new counter accept
  - ip protocol udp ct state established,related,new counter accept
  - ip protocol icmp ct state established,related,new counter accept

  # Allow traffic to the localhost IP address
  - oif "lo" counter accept

  # DHCP client requests
  - udp dport 67 counter log accept
  - udp dport 68 counter log accept

  # DNS requests
  - udp dport 53 counter log accept
  - ip daddr 172.20.100.102/32 tcp dport 53 counter accept
  
  # Block any other connection
  - log level info drop

