---
input_rules:
  # Allow established and related connections
  - ct state established,related counter accept

  # Allow traffic to the loopback interface
  - iif "lo" accept

  # Block unstablished traffics
  - ct state invalid drop

  # Allow proxy access on TCP port 443
  - ip saddr 185.186.243.90/32 tcp dport 443 counter log accept  # sazmane Rahdari
  - ip saddr 109.232.2.194/32 tcp dport 443 counter log accept   # sazmane Rahdari
  - ip saddr 51.79.60.201/32 tcp dport 443 counter log accept    # Morteza Sadeghi

  # Allow SSH from anywhere untill getting whit list IP address
  - ip saddr 51.79.60.201/32 tcp dport 22 counter log accept  # Morteza Sadeghi
  - ip saddr 185.78.23.43/32 tcp dport 22 counter log accept  # Morteza Sadeghi
  - ip saddr 194.164.175.18/32 tcp dport 22 counter log accept # Morteza Sadeghi Spain

  # Allow connection from Trusted IP addresses
  #- ip saddr "ip" counter log accept

  # Allow ICMPv6 incomming traffic
  - icmpv6 type { nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert, echo-request, echo-reply } accept

  # Log and drop all other traffic
  - log level info drop

forward_rules:
# Add forward rules here

output_rules:
  # Allow established and related connections
  - ct state established,related counter accept

  # Allow traffic to the localhost IP address
  - oif "lo" accept

  # DHCP client requests
  - udp dport 67 counter log accept
  - udp dport 68 counter log accept

    # DNS requests
  - udp dport 53 counter log accept

  # Allow web connection traffic
  - tcp dport 443 counter log accept
  - tcp dport 80 counter log accept

  # Allow icmp ping check
  - icmp type echo-request accept

  # Log and drop all other traffic
  - log level info drop
