- name: Remove Cloud init ssh config file
  file:
    path: /etc/ssh/sshd_config.d/50-cloud-init.conf
    state: absent
  ignore_errors: yes

- name: Configure SSH
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
  notify: Restart SSH