- name: Copy Netplan route configuration
  template:
    src: route.j2
    dest: /etc/netplan/99-routes.yaml
    mode: '0600'

# - name: Clean tunnel configs befor apply netplan
#   command: sudo ip link delete tun1

# - name: Apply Netplan configuration
#   command: netplan apply
- name: Restart systemd-networkd 
  command: systemctl restart systemd-networkd.service
  ignore_errors: true
  become: true

- name: Copy iproute2 table configuration
  template:
    src: pbr.j2
    dest: /etc/iproute2/rt_tables
    mode: '0644'