- name: Copy Netplan route configuration
  template:
    src: route.j2
    dest: /etc/netplan/99-routes.yaml
    mode: '0600'

- name: Apply Netplan configuration
  command: netplan apply

- name: Copy iproute2 table configuration
  template:
    src: pbr.j2
    dest: /etc/iproute2/rt_tables
    mode: '0644'