- name: gather packages facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install Squid
  apt:
    name: squid
    state: present
    update_cache: yes
  when:
    - "'squid' not in ansible_facts.packages"

- name: load vault vars
  include_vars:
    file: proxy_users.yml

- name: Update squid users
  community.general.htpasswd:
    path: /etc/squid/squid_passwd
    name: "{{ item.name }}"
    password: "{{ item.pass }}"
    hash_scheme: bcrypt
    mode: '0640'
    owner: proxy
    state: present
  loop: "{{ users }}"
  no_log: true

- name: Configure Squid
  template:
    src: squid.conf.j2
    dest: /etc/squid/squid.conf
  notify: Restart Squid

- name: Start and enable Squid service
  systemd:
    name: squid
    state: started
    enabled: true

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes
