- name: gather packages facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install Squid and dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - squid
    - apache2-utils
    - python3-passlib
  when:
    - "'{{ item }}' not in ansible_facts.packages"

- name: Update htpasswd file for New User
  community.general.htpasswd:
    path: /etc/squid/squid_passwd
    name: "{{ item.key }}"
    password: "{{ item.value }}"
    create: yes
    mode: '0640'
    state: present
  loop: "{{ users | dict2items }}"

- name: Configure Squid
  template:
    src: squid.conf.j2
    dest: /etc/squid/squid.conf
  notify: Restart Squid

- name: Start and enable Squid service
  systemd:
    name: squid
    state: started
    enabled: true

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes


