---
bind_package: bind9
bind_service: bind9
bind_conf_dir: /etc/bind
bind_zone_dir: /etc/bind/zones
bind_named_conf_options: /etc/bind/named.conf.options
bind_named_conf_local: /etc/bind/named.conf.local
bind_named_user: bind
bind_named_group: bind
